name: paynowbloc
description: Paynow implimentation with bloc architecture.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  email_validator: ^1.0.4
  flutter_launcher_icons: ^0.7.4
  flui: ^0.8.0
  splashscreen: ^1.2.0
  bloc: ^4.0.0
  flutter_bloc: ^4.0.1
  paynow: ^1.0.6
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "images/logo.png"
  ios: true
  android: true


flutter:

  uses-material-design: true


  assets:
    - images/logo.png
    - images/logo-blue.png


